### ISSUE TITLE
Geometry Math Tracking Issue

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/super_rogue#2]
- [x] Line-Polygon "is-within"
- [x] Line-Polygon point intersections
- [x] Line-Circle intersections
- [x] Polygon-polygon "union" function for world-gen
- [ ] Move-along-wall code
