### ISSUE TITLE
Inventory / Items Issue Tracker

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/super_rogue#36]
Let's make the player not just have melee and projectile stats, but rather specify these things based on the items in player's possession.

Let's adjust mechanics such that:
- [ ] Damage output reflects equipped items

Let's make displays for:
- [ ] currently equipped items
- [ ] current inventory

As well as actions for:
- [ ] drop item
- [ ] throw item (as if weapon)
- [ ] eat/consume item
- [ ] anything else?
