### ISSUE TITLE
Screen/DPI tracking issue

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/super_rogue#53]
- [ ] Use a higher-DPI font and scale it down
- [ ] Allow any screen aspect ratio to exist -- always fit the map within the current aspect ratio
- [ ] For early levels, use smaller maps
- [ ] Fix the UI in place
