### ISSUE TITLE
New Enemy tracking issue

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/super_rogue#55]
- [ ] Leprechauns at a higher level have "turrets" they place, that shoot the player with a quick bullet when they enter LOS

- [ ] Tripwire -- causes "frozen" status effect. Laid by whom? Maybe "Brute" enemy that simply dashes at the player and beats them up?

- [ ] Enemy with a sword that can reflect bullets using the sword. In order to defeat, must either sneak behind enemy (has slow turning radius), or get in after baiting out attacks (runs out of stamina after 2 slashes)

- [ ] Enemy with a laser eye, that shoots a continuous beam which turns toward the player

- [ ] Bullet hell enemy -- touhou reference?

- [ ] Alligator Wizard that can cast a spell -- a giant polygonal alligator comes from the map boundary and tries to eat the player.
